name: CD Pipeline

on:
  push:
    branches: 
      - main
  workflow_dispatch:  # Permet un déclenchement manuel

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permissions d'écriture
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Utiliser le token GitHub par défaut
      
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
      
      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
      
      - name: Deploy with Helm
        run: |
          helm upgrade --install flask-app ./helm/flask-app --namespace default
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KUBECONFIG: $HOME/.kube/config